app/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)

    from .routes import main
    app.register_blueprint(main)

    return app

app/routes.py
from flask import Blueprint, render_template, request
from .alphavantage import get_stock_info, get_news, get_quote, get_52_week_high_low, check_and_update_data

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/stock_info', methods=['POST'])
def stock_info():
    stock_symbol = request.form['stock_symbol']
    data = get_stock_info(stock_symbol)
    if data is None or "Note" in data or "Error Message" in data:
        error_message = 'Stock symbol not found. Please try again.'
        return render_template('error.html', error_message=error_message)
    news = get_news(stock_symbol)
    quote = get_quote(stock_symbol)
    high_52, low_52 = get_52_week_high_low(stock_symbol)
    
    stock_data = check_and_update_data(stock_symbol)
    dates = [row[1] for row in stock_data]
    closing_prices = [row[5] for row in stock_data]
    #dates, closing_prices = get_daily_time_series(stock_symbol)
    return render_template('stock_info.html', data=data, news = news, quote = quote, high_52 = high_52, low_52 = low_52, dates = dates, closing_prices = closing_prices)

app/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <h1 class="mt-4">Error</h1>
    <p class="text-danger">{{ error_message }}</p>
    <a href="{{ url_for('main.index') }}" class="btn btn-primary">Go Back</a>
</div>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stock Information Lookup</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <h1 class="mt-4">Stock Information Lookup</h1>
    <form action="/stock_info" method="post">
        <div class="form-group">
            <label for="stock_symbol">Stock Symbol:</label>
            <input type="text" class="form-control" id="stock_symbol" name="stock_symbol" required>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
</body>
</html>

app/templates/stock_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stock Information for {{ data['Symbol'] }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
<div class="container">
    <h1 class="mt-4">Stock Information Lookup</h1>
    <form action="/stock_info" method="post", class="mb-4">
        <div class="form-group">
            <label for="stock_symbol">Stock Symbol:</label>
            <input type="text" class="form-control" id="stock_symbol" name="stock_symbol" placeholder="Enter Stock Symbol" required>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <h1>Stock Information for {{ data['Symbol'] }}</h1>
    <p><strong>Company Name:</strong> {{ data['Name'] }}</p>
    <p><strong>Sector:</strong> {{ data['Sector'] }}</p>
    <p><strong>Industry:</strong> {{ data['Industry'] }}</p>
    <p><strong>Market Capitalization:</strong> {{ data['MarketCapitalization'] }}</p>
    <p><strong>PE Ratio:</strong> {{ data['PERatio'] }}</p>
    <p><strong>Earnings Per Share:</strong> {{ data['EPS'] }}</p>
    <p><strong>Dividend Yield:</strong> {{ data['DividendYield'] }}</p>
    <p><strong>Stock Exchange:</strong> {{ data['Exchange'] }}</p>
    <p><strong>Current Price:</strong> {{ quote['Global Quote']['05. price'] }}</p>
    <p><strong>Previous Close:</strong> {{ quote['Global Quote']['08. previous close'] }}</p>
    <p><strong>Open:</strong> {{ quote['Global Quote']['02. open'] }}</p>
    <p><strong>Volumn:</strong> {{ quote['Global Quote']['05. price'] }}</p>
    <p><strong>52 Week High:</strong> {{ high_52 }}</p>
    <p><strong>52 Week Low:</strong> {{ low_52 }}</p>
    <p><strong>News:</strong></p>
    {% for article in news %}
        <div class="news-article">
            <a href="{{ article['url'] }}" target="_blank">{{ article['title'] }}</a>
            <p>{{ article['summary'] }}</p>
        </div>
    {% endfor %}
    
    <div style="width: 100%; height: 600px;">
        <canvas id="stockChart"></canvas>
    </div>
    <script>
        var ctx = document.getElementById('stockChart').getContext('2d');
        var stockChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: {{ dates|tojson }},
                datasets: [{
                    label: 'Closing Price',
                    data: {{ closing_prices|tojson }},
                    borderColor: 'purple',
                    tension: 0.1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: false
                    }
                }
            }
        });
    </script>
</div>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>